### ISSUE TITLE
Video "crop" and mobile cover

### ISSUE THREAD

**Issue by lmartins** [zenoplex/back-tube#13]
On the demo site Im seeing a different behaviour from what Im getting, namely:

1) No black bars - I would like the video to always be cropped and centered so that no black bars appear vertically or horizontally, not finding these in options, is this something that the plugin provides?

2) Mobile Cover - I see that your demo displays a cover instead of the video for mobile devices. Again, is this something the plugin provides or did you achieved outside of the plugin's scope?

**Comment by zenoplex** [comment]
Hi @lmartins 

1) No.  This plugin won't handle removing black bars within the video since there is no way to obtain the width/height of those bars.

2) Partially yes.  Since iOS cannot play video as background using youtube, plugin will detect whether its an iOS device being used via [platform](https://www.npmjs.com/package/platform) plugin.  In that case it will use  `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg` to obtain the cover with best quality as possible.  Currently there are no option to handle which cover image it should obtain.

Sorry, haven't test this with an Android device so I've no idea how it would work.

**Comment by lmartins** [comment]
Thank you so much for your feedback on this @zenoplex 
Looking at your demo it really seemed like the video was being cropped to avoid those black bars, hence my question. Thanks for clarifying that and for the feedback on the video thumb also.

Cheers.
